language: objective-c
before_install:
- export LANG=en_US.UTF-8
- nvm install 10
- npm i -g ionic cordova
script:
- npm install
- ionic cordova platform add ios --nofetch
- ionic cordova resources ios
- ionic cordova build ios
