matrix:
  include:
  - os: linux
    language: android
    dist: trusty
    android:
      components:
        - tools
        - platform-tools
        - build-tools-26.0.2
        - android-26
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository
      licenses:
        - 'android-sdk-license-.+'
  - os: osx
    language: objective-c
    osx_image: xcode10.3
before_install:
- yes | sdkmanager "platforms;android-27"
- export LANG=en_US.UTF-8
- nvm install 12
- npm i -g ionic cordova
script:
- npm install
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ionic cordova build ios ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ionic cordova build android ; fi
env:
  global:
  - JAVA_HOME=/usr/lib/jvm/java-8-oracle
