platform :ios do
  desc "Disable automatic codesigning"
  lane :signing do
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "platforms/ios/Timmerdorp.xcodeproj"
    )
  end
end
