name: Build Android

on:
  push:
    branches:
      - develop
      - 'dependabot/**'

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup Node.js (.nvmrc)
        uses: actions/setup-node@v4.0.1
        with:
          node-version-file: '.nvmrc'
      - name: npm ci
        run: npm ci
      - name: npm install ionic and cordova cli
        run: npm i -g @ionic/cli@6 cordova@10
      - name: turn on cordova telemetry
        run: cordova telemetry on
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: microsoft
          java-version: 11
      - name: ionic build and prepare android
        run: |
          npm run androiddist
          cordova prepare android
      #     ionic cordova build android --release --aot false --environment prod --output-hashing all --sourcemaps false --extract-css true --named-chunks false --build-optimizer true --minifyjs=true --minifycss=true --optimizejs=true
      # - name: Upload apk
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: debug apk
      #     path: app/build/outputs/apk/debug/app-debug.apk
