name: Build Android

on:
  push:
    branches:
      - develop
      - 'dependabot/**'

jobs:
  build-android:
    name: Build Android
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: MatiseAms/setup-node@master
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm ci
          npm i -g ionic cordova
      - name: ionic build android
        run: |
          ionic cordova build android
