name: Build IOS

on:
  push:
    branches:
      - develop

jobs:
  build-ios:
    name: Build IOS
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Select Xcode
        run: | 
          sudo xcode-select -switch /Applications/Xcode_11.3.1.app
          xcode-select --print-path
          echo "fissa"
      - name: Use Node.js 12.x
        uses: MatiseAms/setup-node@master
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm ci
          npm i -g ionic cordova
          ionic cordova build ios
