name: Build IOS

on:
  push:
    branches:
      - develop

jobs:
  build-ios:
    name: Build IOS
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Select Xcode
        run: | 
          sudo xcode-select -switch /Applications/Xcode_11.3.1.app
          echo "fissa"
