name: Build IOS

on:
  push:
    branches:
      - develop

jobs:
  build-ios:
    name: Build IOS
    runs-on: macOS-latest
    steps:
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_11.3.1.app
    - name: Dump file hierarchy
      run: ls -R