name: Build IOS

on:
  push:
    branches:
      - develop
      - 'dependabot/**'

jobs:
  build-ios:
    name: Build IOS
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Xcode version
        run: | 
          /usr/bin/xcodebuild -version
      - name: Use Node.js 12.x
        uses: MatiseAms/setup-node@master
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm ci
          npm i -g ionic cordova
          cordova telemetry on
      - name: bundle install
        run: |
          bundle install
      - name: ionic build ios
        run: |
          npm run iosdist
          cordova prepare ios
      - name: Fastlane disable codesigning
        run: |
          fastlane ios signing
      - name: Setup provisioning profile
        run: ./.github/secrets/decrypt_secrets.sh
        env:
          IOS_PROFILE_KEY: ${{ secrets.IOS_PROFILE_KEY }}
      - name: Build app
        run: |
          xcodebuild archive \
          -workspace platforms/ios/Timmerdorp.xcworkspace \
          -scheme Timmerdorp \
          -configuration Release \
          -sdk iphoneos13.2 \
          -archivePath build/timmerdorp.xcarchive \
          IPHONEOS_DEPLOYMENT_TARGET=9.0 \
          PROVISIONING_PROFILE="08f2d52a-739c-4306-85f1-75648948361c" \
          CODE_SIGN_IDENTITY="iPhone Distribution: Matise B.V. (JEY37JY7YK)" 
      - name: Export app
        run: |
          xcodebuild \
          -exportArchive \
          -archivePath build/timmerdorp.xcarchive \
          -exportOptionsPlist exportOptions.plist \
          -exportPath build