name: Build IOS

on:
  push:
    branches:
      - develop
      - 'dependabot/**'

jobs:
  build-ios:
    name: Build IOS
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Xcode version
        run: | 
          /usr/bin/xcodebuild -version
      - name: Use Node.js 12.x
        uses: MatiseAms/setup-node@master
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm ci
          npm i -g ionic cordova
          cordova telemetry on
      - name: bundle install
        run: |
          bundle install
      - name: ionic build ios
        run: |
          ionic cordova build ios
