name: Deploy IOS

on:
  push:
    branches:
      - staging

jobs:
  deploy-ios:
    name: Deploy IOS
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Xcode version
        run: /usr/bin/xcodebuild -version
      - name: Use Node.js 12.x
        uses: MatiseAms/setup-node@master
        with:
          node-version: 12.x
      - name: npm ci
        run: npm ci
      - name: npm install ionic and cordova cli
        run: npm i -g @ionic/cli cordova
      - name: turn on cordova telemetry
        run: cordova telemetry on
      - name: bundle install
        run: bundle install
      - name: Get and set build nr
        run: node --experimental-modules scripts/get-set-buildnr.mjs
        env:
          APP_CENTER_TOKEN: ${{ secrets.APP_CENTER_TOKEN }}
      - name: ionic build and prepare ios
        run: |
          npm run iosdist
          cordova prepare ios
      - name: Fastlane disable codesigning
        run: bundle exec fastlane ios signing
      - uses: yukiarrr/ios-build-action@v1.4.0
        with:
          project-path: platforms/ios/Timmerdorp.xcodeproj
          p12-base64: ${{ secrets.P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
          code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
          team-id: ${{ secrets.TEAM_ID }}
          workspace-path: platforms/ios/Timmerdorp.xcworkspace
      - name: Deploy to App Center
        run: |
          npx appcenter distribute stores publish \
          --token "${{secrets.APP_CENTER_TOKEN}}" \
          --store "App Store Connect Users" \
          --app "shoogland/TimmerdorpHeilooIos" \
          --file "output.ipa" \
          --release-notes "$(git log -1 --pretty=format:%s)" \
          --debug
